CONTRIBUTING.rst, README.md, pytest_reportportal/pytest_rp_plugin.py, pytest_reportportal/service.py, setup.cfg, setup.py
Report-Portal-Pytest client is added.
=> Pytest-Reportportal client

MANIFEST.in, README.md, pytest_reportportal/service.py, setup.py
Documentation is updated and latest version is uploaded to PyPi server
=> Setup Procedure

pytest_reportportal/__init__.py, pytest_reportportal/service.py
- Now one can log messages from test script at diferent levels (`logger.<loglevel>(...)`).
- Fix `'WARN'` code in `loglevel_map`.
- Add `logger.CRITICAL` code to `loglevel_map`.
=> Fix and improvement of logging

pytest_reportportal/plugin.py
This mistake rises due to two my pull requests from different branches.
=> Fix loglevel type at exception handling.

README.rst, pytest_reportportal/__init__.py, pytest_reportportal/plugin.py, pytest_reportportal/service.py
* async client class is now being used by default by pytest agent.
* added custom Logger to support attachment in log messages;
* added error handler which will prints exceptions from async client-Python thread;
* updated examples with new logging possibilities.
=> Async requests and log attachements

pytest_reportportal/service.py
Changes:
- report test steps as STEP but not a container structure TEST (see screenshots below);
- use the full path to the test step as its name;
- get pytest.mark plugin for tags in a correct way without importing internal _pytest modules.
Before:
After:
=> Fixed the way we report Test Steps to Report Portal

README.rst, pytest_reportportal/service.py
Allow to copy paste and run example from read-me file.
=> Fix handle name in the example.

setup.cfg, setup.py
Do not forget to:
1. Merge this pull request.
2. Set tag `1.0.0` to this commit.
3. Create new release in GitHub.
4. Upload new version to PyPI.
=> Bump up version to 1.0.0

README.rst, pytest_reportportal/plugin.py, pytest_reportportal/service.py
(controlled by rp_ignore_errors cfg option)
=> Do not fail if Report Portal is unreachable

pytest_reportportal/plugin.py
=> Don't launch if `--collect-only` is passed

pytest_reportportal/listener.py
Assume the following test file `test_it.py`:
```python
import pytest
@pytest.fixture
def foo():
return True
@pytest.fixture(scope='session')
def bar(foo):
return False
def test_it(bar):
assert bar is False
```
When running pytest, it will error out because of the fixture scopes.
Previously `pytest_reportportal` would wrongly mark the test as skipped,
with this change it correctly marks it as failed.
Fixes #44
=> Properly report test failures

pytest_reportportal/listener.py, pytest_reportportal/rp_logging.py
Fix issue "AttributeError: 'NoneType' object has no attribute 'post_log'".
Minor fix: set correct log level in emit function
=> fix xdist support

pytest_reportportal/plugin.py, pytest_reportportal/service.py
* test-filename:
* Test Suite:
* Test case
Fixes #47
=> Add support for nested hierarchy test items

pytest_reportportal/listener.py
They will receive the "skip" label so you can distinguish them, so they
require no further action in the interface.  If a test throws skip during
that actual test itself it will still show as "skipped" in reportportal.
Fixes: reportportal/agent-python-pytest#58
=> Make tests that skip in setup phase not require investigation in reportportal

pytest_reportportal/rp_logging.py
Based on discussion happened at #70 raised   This becomes a very needy hack to be integrated into release
=> added the fix to attach screenshots

README.rst, pytest_reportportal/plugin.py
Add description for rp_display_suite_test_file in the readme.md file
=> eden/update_readme_for_new_ini_flag branch PR 

pytest_reportportal/plugin.py, pytest_reportportal/service.py
Added support for "retries" parameter recently added in client-Python
https://github.com/reportportal/client-Python/pull/49
=> Added retries option in accordance with Python client changes

pytest_reportportal/service.py
=> Pass verify_ssl to the RP async service

README.rst, pytest_reportportal/rp_logging.py
=> Fix patching of non-RP loggers

pytest_reportportal/plugin.py, pytest_reportportal/service.py, setup.py, tests/test_plugin.py
=> Terminate service correctly with the maxfail option

README.rst, pytest_reportportal/listener.py, pytest_reportportal/plugin.py, pytest_reportportal/service.py, setup.py, tests/test_plugin.py
This PR includes fixes from #146 along with working logging. It won't work with the xdist plugin.
=> Fixes for async v5 support

pytest_reportportal/service.py, setup.py, tests/test_service.py
=> Do not pass parameters as empty dictionary

pytest_reportportal/service.py
=> Fix parentness relations when nested hierarchy takes place

pytest_reportportal/plugin.py
I have not able to found any impact from that sorting other than the problem depicted in #130.
=> Remove items sorting

pytest_reportportal/service.py, setup.py
=> Send item_type for the test item as STEP

pytest_reportportal/service.py
=> fix logging typo

README.rst, pytest_reportportal/plugin.py, tests/test_plugin.py
=> Allow passing key/value attributes to RP

.travis.yml, pytest_reportportal/service.py, requirements.txt, setup.py, tests/test_service.py
=> Convert LocalPath objects to strings

pytest_reportportal/service.py
Fixes #233
I have not found any unit tests for this component to add this check, seems that there is no unit tests yet for the component. .
I`ll be happy to increase unit test coverage in a next pull request.
=> Fix missed log_batch_size in init_service().

pytest_reportportal/plugin.py, pytest_reportportal/service.py
simply add `--rp-rerun` with or without `--rp-rerun-of xxxx-xxxx-xxxx-xxxx` to indicate the current session should be a rerun of the recent or specific launch
=> implement rerun functionality

pytest_reportportal/rp_logging.py, requirements.txt, setup.py
=> Remove trailing slash when filtering log messages

pytest_reportportal/service.py, setup.py
=> Clear parent item id sending out the last child test result

pytest_reportportal/plugin.py
added ability to push --rp_project from command line
=> added ability to provide rp_project from command line

pytest_reportportal/rp_logging.py
Fixes [#113 ](https://github.com/reportportal/client-Python/issues/113)
=> WIP: Filter urllib3 message correctly

pytest_reportportal/config.py, tests/conftest.py
=> Fix `AttributeError` in `AgentConfig.find_option`

pytest_reportportal/service.py
For more information, please refer to my bug ticket
=> PR for issue #277

examples/test_rp_logging.py, pytest_reportportal/listener.py, tests/helpers/utils.py, tests/integration/test_logging_flush.py, tests/integration/test_suite_hierarchy.py
=> Log buffer flushing

pytest_reportportal/service.py
Resolves #294 
No tests because this part of the code is gonna be refactored soon.
=> Process command-line rp_parent_item_id correctly

README.rst
Add missing `rp_hierarchy_code`  parameter to README.md
=> Update Readme file

README.rst, examples/threads/test_thread_logging.py, pytest_reportportal/config.py, pytest_reportportal/plugin.py, pytest_reportportal/rp_logging.py, tests/integration/test_empty_run.py, tests/integration/test_threads_logs.py, tests/unit/test_plugin.py
This comes as a solution for #310 which was closed due to limitations in the python threading module.
=> Add support for thread logs

pytest_reportportal/service.py
=> Updating attributes before finish test_item

README.rst
RPv4 has been obsolete for quite some time now
=> remove RPv4 notice from README
