reportportal/agent-python-pytest

- pytest_reportportal/plugin.py
This changeset provide logging of PyTest exceptions (see issue #4). It looks like this:
> Primitive logging of PyTest exception messages

- README.rst
- Fixed syntax issue in the logging example.
- Add ability to copy paste example and run test.
> Fix logging example, make it ready to copy-paste.

- README.rst
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
- setup.py
Changes:
- added rp_launch and rp_launch_description config options;
- rp_launch option has a default value so it is no longer mandatory;
- CLI option --rp_launch will override rp_launch config option;
- updated help strings for options and README file;
- extract names of Pytest markers (decorators like @pytest.mark.linux, @pytest.mark.win32 etc) and use them as Tags for Items on Report Portal;
- Add descriptions and tags usage examples to README.
> Add launch name config option and tags for test items

- README.rst
- pytest_reportportal/service.py
In some cases there is no traceback printed if there is an issue with Report Portal (e.g. invalid uuid). Only error message appeared.
Also updated readme with some notes about disabling plug-in.
> Enhance traceback printing and readme file.

- pytest_reportportal/plugin.py
> Send error log after the test item session started.

- pytest_reportportal/plugin.py
This adds workaround for issue #29 till full architecture re-implementation.
Current implementation of Report Portal `pytest` agent is not compatible with distributed tests execution.
Thus, following workaround has been added to notify end user about this problem.
User will get exception in case when plug-in `xdist` is installed  with output like:
```bash
$ pytest -n 4 --rp-launch TestRPIssue29 test_script.py
...
INTERNALERROR> Exception: pytest report portal is not compatible with 'xdist' plugin.
```
If it is required to have this plug-in installed for e.g. `unittest`, this plug-in can be temporary disabled for test which running with Repor Portal integration:
```bash
$ pytest -p no:xdist --rp-launch TestRPIssue29 test_script.py
```
> Raising exception when using 'xdist' plug-in

- pytest_reportportal/service.py
As was noted in the `pytest-dev@python.org` mailing list, 
> `MarkMapping` is only complete enough to fulfill its internal use case.
That is why was decided to duplicate logic of `from_keyword` class method in our plug-in. 
Other solution with checking existence of attributes and parsing `pytest` version looks even worser personally for me.
> Add fix for issue #37

- pytest_reportportal/service.py
Get rid of code duplicity in favor to use special method for getting marks. This fixes issue #37.
Tested on `python3`.
Many thanks @RonnyPfannschmidt for help!
> Enhanced fix for issue #37

- pytest_reportportal/rp_logging.py
There was a failure while using the report portal pytest plugin on python 2.7 which resulted in following error message: `TypeError: findCaller() takes exactly 1 argument (2 given)`.
The fix is doing the check for the python version on the system and select the appropriate way of calling `findCaller()` and `makeRecord()` functions from logging module.
> Bugfix for python2.7 compatibility issue #45

- pytest_reportportal/service.py
`reportportal_client.errors.ResponseError: 4001: Incorrect Request. [Field 'name' should have size from '1' to '256'.]`
See https://reportportal.slack.com/archives/C2GTJTTNH/p1514306996000087
> Truncate test name to maximum allowed length of 256 chars.

- pytest_reportportal/listener.py
When some test was skipped in the setup, RP wrongly identified its
status, by assigning to it the status of the last non-skipped test.
Test to reproduce:
```
import pytest
@pytest.fixture
def skip_in_setup():
pytest.skip()
def test_that_fails():
assert False
@pytest.mark.usefixtures("skip_in_setup")
def test_skip_in_setup(self):
pass
```
In this example the first test fails and the second is skipped.
RP identified both as failures.
> Fix case of incorrect status when test was skipped in setup.

- pytest_reportportal/listener.py
- pytest_reportportal/plugin.py
- pytest_reportportal/rp_logging.py
* Fix log level evaluation. Both option and INI setting must default to None.
* Filter out log messages from `urllib3.connectionpool` if the value of `rp_entpoint` is in the log string
> Fix log_level evaluation. Fix and simplify logging filtering.

- pytest_reportportal/service.py
The original code assumed that all test items were subclasses of "Function",
but they aren't.  The easy case is PyFlakes tests, but there are many more
examples.
So use an explicit sentinel instead of assuming.
Fixes: reportportal/agent-python-pytest#66
> Fix test item nesting for non-Function tests.

- README.rst
- pytest_reportportal/plugin.py
ReportPortal plugin disabled by default. For enabling pytest-reportportal plugin you should provide --reportportal flag.
Resolve issue #64
> enable implicit plugin usage

- README.rst
- pytest_reportportal/rp_logging.py
- adding check for logging class patching to avoid double patching. Fix #70
- changes in readme file example: fixture scope was changed to "session" and adding handler to logger was removed
> Fix for double patching logger class

- README.rst
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
- new hierarchy levels for module directories and parametrized tests;
- ability to configure report hierarchy via pytest.ini;
- generating hierarchy item name depends on configuration;
- hierarchy item result now depends on nested tests results.
Example
dir1/dir2/module1.py::TestClass1::test1 [param1=1]
dir1/dir2/module1.py::TestClass1::test1 [param1=2]
dir1/dir2/module1.py::TestClass1::test2
```
for: hier_dir =1, hier_module=1, hier_class=1, hier_param=0, hier_dir_level=0
we report: dir1 -> dir2 -> module1.py -> TestClass1 -> test1 [param1=1]
-> test1 [param1=2]
-> test2
for: hier_dir =1, hier_module=1, hier_class=1, hier_param=0, hier_dir_level=1
we report: dir2 -> module1.py -> TestClass1 -> test1 [param1=1]
-> test1 [param1=2]
-> test2
for: hier_dir =0, hier_module=1, hier_class=1, …
```
> New report hierarchy abilities

- pytest_reportportal/plugin.py
i believe there is a bug: 
https://github.com/reportportal/agent-python-pytest/issues/80#issuecomment-417326908
and this should fix it
> fixed the attribute name _reportportal_enabled to _reportportal_configured

- README.rst
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
- Adding new pytest ini option `rp_tests_tags`, to add tags for each items in the launch
- Removing docstring indentations for item description (see https://www.python.org/dev/peps/pep-0257/)
Previous docstring format:
New docstring format:
> Removing docstring indentations and adding tags for each items in the launch

- pytest_reportportal/service.py
Packages can cause issue with incorrect hierarchy on new versions of pytest
> Fix for issue with pytest Package

- pytest_reportportal/service.py
when `rp_hierarchy` feature is being used, the plugin crashes if it is unable to locate any pytest `Function` components. This is a problem if one uses `unittest` test cases, since they use different classes.
This PR adds 2 more calls to `_add_item_hier_parts_other` for filtering out unittest's `UnitTestCase` (equivalent of `_pytest.python.Class`) and `TestCaseFunction` (equivalent of `_pytest.python.Function`)
> add support for python unittest hierarchy

- README.rst
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
This builds on https://github.com/reportportal/client-Python/pull/33 to add an `verify_ssl` option to the pytest ini file. This allows the library to be used with self signed certs without having to add the cert to requests
Edit: `ignore_ssl` -> `verify_ssl`
> Add ignore ssl rules

- README.rst
rp parameters that are in pytest.ini can be overridden by passing -o command line option. Readme has been updated indicating that.
> Update readme about overriding rp parameters from command line.

- pytest_reportportal/service.py
```
@pytest.mark.rank(1)
def test_foo:
pass
```
would result in the following tag: `rank:1` added to the test item.
> Include a marker value, if present, when tagging tests.

- README.rst
- pytest_reportportal/listener.py
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
- Add ability to specifity comment and issue type via pytest marks for test fails
- Fixing pytest warnings for using deprecated code for pytest marks. See https://docs.pytest.org/en/latest/mark.html#updating-code
Some pytest marks could be used to specify information about skipped or failed test result.
List of this marks should be specified in pytest ini file (see `rp_issue_marks`).
The following mark fields are used to get information about test issue:
- `issue_id` - issue id in tracking system. This id will be added as comment to test fail result. If URL is specified in pytest ini file (see `rp_issue_system_url`), id will added as link to tracking system.
- `reason` - some comment that will be added to test fail description.
- `issue_type` - short name of RP issue type that should be …
> Adding issue info to test result in RP

- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
Add the rp_display_suite_test_file twick which is relevant only when
"rp_hierarchy_module" flag is False
Setting this 'rp_display_suite_test_file' pytest.ini flag to True will make sure that in case the rp_hierarchy_module was set to False, then the suite name will not be:
<PATH_TO_FILE>::<SUIT_NAME>
But it will just the SUITE_NAME
Edit the collect_tests of PyTestServiceClass to support the new
display_suite_file_name twik
> Add rp_display_suite_test_file to pytest.ini flags

- README.rst
- pytest_reportportal/listener.py
- pytest_reportportal/service.py
1) Getting project settings if client support this
2) `html.escape` instead `cgi.escape` if possible, to disable warnings in python3
3) Small updates in generating issue comment
> Getting project settings if client support it

- setup.py
Fix for "HTTPError: 400 Client Error: The description failed to render in the default format of reStructuredText" (Jenkins [console](http://jenkins.epm-rpp.projects.epam.com:8181/job/agent-python-pytest/18/console))
> fix README rendering error

- pytest_reportportal/rp_logging.py
I faced with an issue when attachment I send to rp_logger.info was empty in some cases. Going through the code, I noticed that wrap_makeRecord actually handles situations when "attachment" is in the "extra" parameter and then performs record.attachment = attachment (at the end of wrap_makeRecord -> makeRecord method). But when wrapper finishes, right in the next line code overwrites correct value of record.attachment with None value.
> record.attachment overwritten by None value

- pytest_reportportal/service.py
According to PyTest changes: https://github.com/pytest-dev/pytest/commit/fd48cd57f95d2c4e2f6f4e416d20c36b4484d094
Fixes https://github.com/reportportal/agent-python-pytest/issues/120
> Fix warning adding if test name is longer then 256 chars

- pytest_reportportal/listener.py
- pytest_reportportal/service.py
- Fix exception on empty issue type:
```
reportportal_client.errors.ResponseError: 4001: Incorrect Request. [Field 'issue.issueType' shouldn't be null.]
```
- Disabling escaping for quotes in logs:
Compare:
`[&#x27;special-vector&#x27;, &#x27;packet-types&#x27;, &#x27;no-per-ip&#x27;];`
and:
`['special-vector', 'packet-types', 'no-per-ip']`
- fix for typo in `service.project_settiings`
> Fixes for fail on empty issue type and disabling quotes escaping

- .travis.yml
- pytest_reportportal/plugin.py
- setup.cfg
- setup.py
- tests/test_plugin.py
This is an improved version of https://github.com/reportportal/agent-python-pytest/pull/100 with unit tests.
> Stop plugin configuration if ReportPortal connection fails

- .travis.yml
- README.rst
- setup.py
What's in?
1. Bumped the version up to 1.0.8 to align releases at GitHub and version at PyPi.
2. Disable deployment on forks.
> Update an example of the python logging handler usage

- pytest_reportportal/rp_logging.py
Hello, I have the same issue as #70 with curcrent versions: 
pytest                               4.6.6
pytest-reportportal         1.0.8
reportportal-client          3.2.3
The `pytest_runtest_protocol` wrapper in `listener.py` does restore the patching, but doesn't allow re-patching of the logger class.  This patch remove the `_patched` attribute, so the logger class can be patched again.
Thank you!
> rp_logging: Remove '_patched' when 'patching_logger_class' finished.

- pytest_reportportal/plugin.py
- pytest_reportportal/rp_logging.py
- tests/test_plugin.py
* fix for logger issue:
```
INTERNALERROR>   File "/usr/lib/python3.6/logging/__init__.py", line 1308, in info
INTERNALERROR>     self._log(INFO, msg, args, **kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pytest_reportportal/rp_logging.py", line 48, in _log
INTERNALERROR>     if not record.attachment:
INTERNALERROR> AttributeError: 'LogRecord' object has no attribute 'attachment'
```
* adding support for pytest `--setup-plan` option
* code optimization for `config._reportportal_configured`
> Fix logging issue and adding support for pytest --setup-plan option

- README.rst
- pytest_reportportal/listener.py
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
- tests/test_plugin.py
- Adds ability to add issue-id marks (tags) to the test (e.g. issue:23467)
- Support ability to adding item marks inside test or fixture
- Fix issue when teadworn fixture is failed but test result is passed
See also: https://github.com/reportportal/client-Python/pull/63
> Adding support for issue-id marks

- setup.py
Update reportportal-client version requirement to avoid installations of 4.0.0 version of the client.
> Update common client version requirement

- pytest_reportportal/plugin.py
- setup.py
> Reflect get_actual_log_level() name change in Pytest

- .travis.yml
- pytest_reportportal/listener.py
- pytest_reportportal/service.py
- setup.py
- tests/__init__.py
- tests/conftest.py
- tests/test_plugin.py
What was done:
- dropped support for Python 3.4 due to EOL
- fixed an issue with the 'issue' marker reporting
- reorganized unit tests
- added test stages for Python 3.7 and Python 3.8
- added reporting of the system information to the launch
> Fix reporting of an issue marker.

- .gitignore
- README.rst
- pytest_reportportal/plugin.py
- setup.py
- tests/test_plugin.py
- tests/test_service.py
This adds an environment variable override for the pytest.ini attribute `rp_uuid`. When the `RP_UUID` is set it will override the rp_uuid attribute value. The purpose for this is to set an environment variable so the `rp_uuid` does not have to be checked in to the git repository. I am happy to make further changes to set some of the pytest options to be configurable as env variables.
> add env var override for rp_uuid

- pytest_reportportal/plugin.py
- tests/test_plugin.py
Fixed issue https://github.com/reportportal/agent-python-pytest/issues/125
+ Added check if response have word Maintenance in text;
+ Added unit tests.
> Fixed tests not running when report portal on maintenance

- pytest_reportportal/helpers.py
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
- tests/test_helpers.py
- tests/test_plugin.py
- tests/test_service.py
get_attributes function was moved to a new helpers module. Item attributes can now be added as key/value pairs both in pytest.ini and in decorators
> Make it possible to add item attributes as key/value pairs, not just values

- README.rst
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
**depends on**: https://github.com/reportportal/client-Python/pull/133
This implements the RFE #156 - we're now able to specify `--rp_launch_id <launch uuid>` cli option(or `launch_id` option in `pytest.ini`) to be used by the RP logger.
When used, the logger doesn't control the launch (start/finish) and we're free to control it by external script (e.g. jenkins pipeline).
Since this depends on https://github.com/reportportal/client-Python/pull/133 to be merged and released, this PR should also include the bumped version of the client-Python package in `requirements.txt`.
> fixes #156 - implement rp_launch_id parameter to specify an existing launch to be used by the session

- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
fixes #225
The fix is really easy and it is also backwards compatible (with xdist<2)
The compatibility broke just because upstream removed deprecated alias:
https://github.com/pytest-dev/pytest-xdist/pull/541/files#diff-8db1df3356c9e2971831603998e197e0015b6cb52edcc77eb45ef00210440768L237
All we have to do is to refer to the `workerinput`.
> fixes #225 - add support for pytest-xdist v2

- pytest_reportportal/plugin.py
- tests/test_plugin.py
the current implementation completely ignores the cli option: `--rp-launch-id` and directly uses the value from the ini file.
This commit fixes it.
> Fix --rp-launch-id parsing

- README.rst
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
Similar to `rp_launch_id`, this adds an option to specify a custom item ID to be used as a parent for all tests across the pytest session.
This is useful when there's a need to build a custom `Launch->level1->...->leveln` test suite structure`
e.g. if users run automation in multiple processes and want to push results to a single Suite.
This also enables usage of `rp_rerun` together with `pytest-xdist` sessions (flat hierarchy), as there's currently a [bug](https://github.com/reportportal/reportportal/issues/1249) which prevents reruns on root-level items.
> implement using of custom parent_item for the pytest session

- requirements.txt
`reportportal-client` v. 5.0.7 contains [the code](https://github.com/reportportal/client-Python/commit/5766704ef7590170acb47704fb7c10b64fe8e283) required by the `--rp-launch-id` option.
> Bump the dependency version to support --rp-launch-id

- pytest_reportportal/service.py
- tests/test_service.py
Report Portal supports having Attributes with same keys. This is important when filtering data on dashboards and having similar attributes on same level. Also helpful in grouping tests. 
New Contributor Alert, Please let me know, if there is anything I missed or need to do to have pr reviewed
> Adds support to have attributes with same keys

- pytest_reportportal/plugin.py
This patch resolves the deprecation warning below.
```
/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/pytest_reportportal/plugin.py:46: PytestDeprecationWarning: The hookimpl pytest_configure_node uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(optionalhook=True) decorator instead
to configure the hooks.
See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
@pytest.mark.optionalhook
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
> Change pytest.mark.optionalhook to pytest.hookimpl to resolve PytestDeprecationWarning

- pytest_reportportal/config.py
- pytest_reportportal/plugin.py
- pytest_reportportal/service.py
- tests/unit/test_plugin.py
Hellow,
This PR handles 2 things:
1. Fixes an issue with `rp_dir_level`: in `_remove_root_dirs`, the loop that handles the ROOT node only handled it first child and called `return`.
2. Add back the support for `rp_display_suite_test_file`. It depends on `rp_dir_level` in a way that if the file name appears deep in the hierarchy, it will be kept and not deleted. The default is `True` to keep the current behavior, but if set to `False`, and the `rp_dir_level` is deep enough, the file name will be removed too, and will be left with suites and tests only in the hierarchy.
> Restore rp_display_suite_test_file and fix bug with rp_dir_level

- pytest_reportportal/config.py
Allows the same behaviour for `rp_endpoint` flag (when defined in pytest.ini for example) as is currently for `rp_api_key` - which is the ability to be overridden by an environment variable.
> Allow rp endpoint override
